export interface LeaveRecord {
  id?: string; // Ideally generated by backend, but we might use timestamp/index
  name: string;
  type: 'Casual' | 'Sick' | 'Duty';
  applyDate: string;
  startDate: string;
  endDate: string;
  days: number;
  method: string;
  timestamp?: string;
}

export interface Teacher {
  name: string;
}

export interface TeacherSummary {
  name: string;
  casualTaken: number;
  sickTaken: number;
  dutyTaken: number;
}

export interface AppData {
  teachers: string[];
  history: LeaveRecord[];
}

export interface ApiResponse {
  status: 'SUCCESS' | 'ERROR';
  data?: AppData;
  message?: string;
}